### ISSUE TITLE
Different configurations for sources and tests

### ISSUE THREAD

**Issue by SimonHarmonicMinor** [synergy-au/pmd-analyser-action#4]
I have `pmd_main.xml` and `pmd_test.xml` in my project. Is it possible to configure separate configurations for sources and tests?

**Comment by Clint-Chester** [comment]
Yeah it should be possible depending on how you've got your workflow setup. There's a couple of options you can look into:

- In the `rules-path` you can pass both those rule files in (haven't tested but it should work). This would probably only be applicable depending on how you've got your jobs structured and whether you were comparing file diffs vs. just specifying file paths.

```
- name: Run PMD Analyser
    id: pmd-analysis
    uses: synergy-au/pmd-analyser-action@v2
    with:
      pmd-version: '6.35.0'
      file-path: './src'
      rules-path: './pmd_main.xml,./pmd_test.xml'
```
- If your workflow is running different jobs you can just have one job specified for sources and one job specified for tests, then just run the analysis in parallel.

If you've got an example workflow file that you are contending with I'm happy to provide further input 😄
